"""
MODULE NAME: vision_model.py
====================================
Execution Location: market-hawk-mvp/ml/
Purpose: Chart pattern recognition using transfer learning (ResNet50).
Hardware Optimization: Intel i7-9700F, NVIDIA GTX 1070 8GB VRAM, 64GB DDR4
Creation Date: 2026-03-08

Components:
    - ChartPatternDataset: Lazy-loading PyTorch Dataset from manifest CSV
    - ChartPatternClassifier: ResNet50 backbone with custom classification head
    - ChartTrainer: Training loop with mixed precision, checkpointing, metrics
    - predict_chart(): Single-image inference function

Designed for ~98K chart images, optimized for 8GB VRAM with mixed precision.
"""

import gc
import hashlib
import json
import logging
import os
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset

logger = logging.getLogger("market_hawk.ml.vision_model")

# ============================================================
# CONSTANTS
# ============================================================

# ImageNet normalization (RGB)
IMAGENET_MEAN: Tuple[float, ...] = (0.485, 0.456, 0.406)
IMAGENET_STD: Tuple[float, ...] = (0.229, 0.224, 0.225)

# Default input resolution
INPUT_SIZE: int = 224

# Safe batch sizes for GTX 1070 8GB VRAM (ResNet50 fp16)
BATCH_SIZE_OPTIONS: List[int] = [32, 16, 8, 4]

# Default training hyperparameters
DEFAULT_LR: float = 1e-4
DEFAULT_EPOCHS: int = 50
EARLY_STOPPING_PATIENCE: int = 10
NUM_CHECKPOINTS_KEEP: int = 3


# ============================================================
# DATA CLASSES
# ============================================================

@dataclass
class TrainingMetrics:
    """Metrics for a single epoch."""
    epoch: int
    train_loss: float
    train_accuracy: float
    val_loss: float
    val_accuracy: float
    val_precision: float = 0.0
    val_recall: float = 0.0
    val_f1: float = 0.0
    lr: float = 0.0
    elapsed_sec: float = 0.0
    gpu_memory_mb: float = 0.0


@dataclass
class TrainingReport:
    """Full training run report."""
    model_name: str
    num_classes: int
    class_names: List[str]
    total_epochs: int
    best_epoch: int
    best_val_accuracy: float
    best_val_f1: float
    epoch_metrics: List[TrainingMetrics] = field(default_factory=list)
    train_samples: int = 0
    val_samples: int = 0
    test_samples: int = 0
    total_elapsed_sec: float = 0.0
    confusion_matrix: Optional[List[List[int]]] = None

    def summary(self) -> str:
        """Format human-readable training summary."""
        lines = [
            "=" * 60,
            "CHART VISION MODEL TRAINING REPORT",
            "=" * 60,
            f"Model:              {self.model_name}",
            f"Classes:            {self.num_classes} ({', '.join(self.class_names[:5])}...)"
            if len(self.class_names) > 5 else
            f"Classes:            {self.num_classes} ({', '.join(self.class_names)})",
            f"Train samples:      {self.train_samples:,}",
            f"Val samples:        {self.val_samples:,}",
            f"Test samples:       {self.test_samples:,}",
            f"Total epochs:       {self.total_epochs}",
            f"Best epoch:         {self.best_epoch}",
            f"Best val accuracy:  {self.best_val_accuracy:.4f}",
            f"Best val F1:        {self.best_val_f1:.4f}",
            f"Total time:         {self.total_elapsed_sec:.1f}s",
            "=" * 60,
        ]
        return "\n".join(lines)


# ============================================================
# DATASET
# ============================================================

class ChartPatternDataset(Dataset):
    """Lazy-loading chart image dataset from manifest CSV.

    Reads the manifest CSV generated by prepare_chart_dataset.py.
    Images are loaded on-the-fly (lazy loading) to conserve RAM.
    Supports training augmentations and validation transforms.

    Args:
        manifest_path: Path to the manifest CSV file.
        label_column: Column name to use as classification target.
        transform: torchvision transform pipeline.
        label_to_idx: Optional pre-built label-to-index mapping.
            If None, builds from manifest data.
        filter_unlabeled: If True, skip rows where label == "unlabeled".
    """

    def __init__(
        self,
        manifest_path: str,
        label_column: str = "label",
        transform: Any = None,
        label_to_idx: Optional[Dict[str, int]] = None,
        filter_unlabeled: bool = True,
    ) -> None:
        self.manifest_path = Path(manifest_path)
        self.label_column = label_column
        self.transform = transform
        self.filter_unlabeled = filter_unlabeled

        # Load manifest
        df = pd.read_csv(self.manifest_path)
        if filter_unlabeled:
            df = df[df[label_column] != "unlabeled"].reset_index(drop=True)

        self.image_paths: List[str] = df["image_path"].tolist()
        self.labels_raw: List[str] = df[label_column].tolist()

        # Build or use provided label mapping
        if label_to_idx is not None:
            self.label_to_idx = label_to_idx
        else:
            unique_labels = sorted(set(self.labels_raw))
            self.label_to_idx = {lbl: i for i, lbl in enumerate(unique_labels)}

        self.idx_to_label: Dict[int, str] = {
            v: k for k, v in self.label_to_idx.items()
        }
        self.num_classes: int = len(self.label_to_idx)

        logger.info(
            "Dataset loaded: %d samples, %d classes from %s",
            len(self), self.num_classes, self.manifest_path.name,
        )

    def __len__(self) -> int:
        return len(self.image_paths)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        """Load a single image and return (tensor, label_index).

        Args:
            idx: Sample index.

        Returns:
            Tuple of (image_tensor, label_index).
        """
        from PIL import Image

        img_path = self.image_paths[idx]
        label_str = self.labels_raw[idx]
        label_idx = self.label_to_idx.get(label_str, 0)

        # Load image, convert to RGB
        try:
            img = Image.open(img_path).convert("RGB")
        except Exception as e:
            logger.warning("Failed to load image %s: %s", img_path, e)
            # Return a black placeholder image
            img = Image.new("RGB", (INPUT_SIZE, INPUT_SIZE), (0, 0, 0))

        if self.transform is not None:
            img = self.transform(img)
        else:
            # Fallback: basic tensor conversion
            from torchvision import transforms
            img = transforms.Compose([
                transforms.Resize((INPUT_SIZE, INPUT_SIZE)),
                transforms.ToTensor(),
                transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
            ])(img)

        return img, label_idx

    @property
    def class_names(self) -> List[str]:
        """Return ordered list of class names."""
        return [self.idx_to_label[i] for i in range(self.num_classes)]


def get_train_transforms() -> Any:
    """Build training augmentation pipeline.

    Returns:
        torchvision.transforms.Compose for training data.
    """
    from torchvision import transforms
    return transforms.Compose([
        transforms.Resize((INPUT_SIZE, INPUT_SIZE)),
        transforms.RandomHorizontalFlip(p=0.5),
        transforms.ColorJitter(
            brightness=0.2, contrast=0.2, saturation=0.1, hue=0.05,
        ),
        transforms.RandomRotation(degrees=5),
        transforms.ToTensor(),
        transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ])


def get_val_transforms() -> Any:
    """Build validation/test transform pipeline (no augmentation).

    Returns:
        torchvision.transforms.Compose for validation/test data.
    """
    from torchvision import transforms
    return transforms.Compose([
        transforms.Resize((INPUT_SIZE, INPUT_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
    ])


# ============================================================
# MODEL
# ============================================================

class ChartPatternClassifier(nn.Module):
    """ResNet50-based chart pattern classifier with transfer learning.

    Architecture:
        - Backbone: ResNet50 pretrained on ImageNet
        - Freeze: First 3 residual blocks (layer1, layer2, layer3)
        - Fine-tune: layer4 + custom classification head
        - Head: AdaptiveAvgPool2d -> Dropout(0.3) -> Linear(2048, 512)
                -> ReLU -> Dropout(0.2) -> Linear(512, num_classes)

    Args:
        num_classes: Number of output classes.
        pretrained: Whether to use ImageNet pretrained weights.
        dropout_head: Dropout rate for the first dropout layer.
        dropout_classifier: Dropout rate for the second dropout layer.
    """

    def __init__(
        self,
        num_classes: int,
        pretrained: bool = True,
        dropout_head: float = 0.3,
        dropout_classifier: float = 0.2,
    ) -> None:
        super().__init__()
        self.num_classes = num_classes

        # Load pretrained ResNet50
        from torchvision import models
        if pretrained:
            weights = models.ResNet50_Weights.IMAGENET1K_V2
            self.backbone = models.resnet50(weights=weights)
        else:
            self.backbone = models.resnet50(weights=None)

        # Freeze early layers (conv1, bn1, layer1, layer2, layer3)
        frozen_modules = [
            self.backbone.conv1,
            self.backbone.bn1,
            self.backbone.layer1,
            self.backbone.layer2,
            self.backbone.layer3,
        ]
        for module in frozen_modules:
            for param in module.parameters():
                param.requires_grad = False

        # Replace the default FC head
        backbone_out_features = self.backbone.fc.in_features  # 2048
        self.backbone.fc = nn.Identity()

        # Custom classification head
        self.classifier = nn.Sequential(
            nn.AdaptiveAvgPool1d(1) if False else nn.Identity(),
            nn.Dropout(p=dropout_head),
            nn.Linear(backbone_out_features, 512),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout_classifier),
            nn.Linear(512, num_classes),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass.

        Args:
            x: Input tensor of shape (batch, 3, 224, 224).

        Returns:
            Logits tensor of shape (batch, num_classes).
        """
        features = self.backbone(x)  # (batch, 2048) after avgpool + flatten
        logits = self.classifier(features)
        return logits

    def get_trainable_params(self) -> int:
        """Count trainable parameters."""
        return sum(p.numel() for p in self.parameters() if p.requires_grad)

    def get_total_params(self) -> int:
        """Count total parameters."""
        return sum(p.numel() for p in self.parameters())


# ============================================================
# TRAINER
# ============================================================

class ChartTrainer:
    """Training loop for ChartPatternClassifier with mixed precision.

    Features:
        - Mixed precision (torch.cuda.amp) for 8GB VRAM optimization
        - Automatic batch size reduction on OOM
        - Cosine annealing LR scheduler
        - Early stopping with configurable patience
        - Checkpoint management (keep best N)
        - Per-epoch metrics: accuracy, precision, recall, F1
        - Confusion matrix on validation set
        - Memory cleanup after each epoch

    Args:
        model: ChartPatternClassifier instance.
        train_dataset: Training dataset.
        val_dataset: Validation dataset.
        output_dir: Directory for checkpoints and reports.
        batch_size: Initial batch size (auto-reduced on OOM).
        lr: Learning rate.
        epochs: Maximum training epochs.
        patience: Early stopping patience.
        num_workers: DataLoader workers.
        device: torch device string.
    """

    def __init__(
        self,
        model: ChartPatternClassifier,
        train_dataset: ChartPatternDataset,
        val_dataset: ChartPatternDataset,
        output_dir: str = "models/vision",
        batch_size: int = 32,
        lr: float = DEFAULT_LR,
        epochs: int = DEFAULT_EPOCHS,
        patience: int = EARLY_STOPPING_PATIENCE,
        num_workers: int = 4,
        device: Optional[str] = None,
    ) -> None:
        self.model = model
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.batch_size = batch_size
        self.lr = lr
        self.max_epochs = epochs
        self.patience = patience
        self.num_workers = num_workers

        # Device setup
        if device is not None:
            self.device = torch.device(device)
        elif torch.cuda.is_available():
            self.device = torch.device("cuda")
        else:
            self.device = torch.device("cpu")

        self.model.to(self.device)
        logger.info("Device: %s", self.device)
        if self.device.type == "cuda":
            logger.info("GPU: %s (%.1f GB VRAM)",
                         torch.cuda.get_device_name(0),
                         torch.cuda.get_device_properties(0).total_memory / 1e9)

        # Loss function with class weights for imbalanced data
        self.criterion = nn.CrossEntropyLoss()

        # Optimizer: only trainable params
        self.optimizer = torch.optim.AdamW(
            filter(lambda p: p.requires_grad, self.model.parameters()),
            lr=self.lr,
            weight_decay=1e-4,
        )

        # LR scheduler: cosine annealing
        self.scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
            self.optimizer, T_max=self.max_epochs, eta_min=1e-6,
        )

        # Mixed precision scaler
        self.scaler = torch.cuda.amp.GradScaler(enabled=(self.device.type == "cuda"))
        self.use_amp = self.device.type == "cuda"

        # DataLoaders (created with auto batch size)
        self.train_loader: Optional[DataLoader] = None
        self.val_loader: Optional[DataLoader] = None
        self._create_dataloaders()

        # Tracking
        self.best_val_accuracy = 0.0
        self.best_val_f1 = 0.0
        self.best_epoch = 0
        self.epochs_without_improvement = 0
        self.checkpoint_paths: List[Path] = []
        self.epoch_metrics: List[TrainingMetrics] = []

    def _create_dataloaders(self) -> None:
        """Create DataLoaders with current batch size.

        Tries progressively smaller batch sizes if OOM is detected
        during the first training step.
        """
        self.train_loader = DataLoader(
            self.train_dataset,
            batch_size=self.batch_size,
            shuffle=True,
            num_workers=self.num_workers,
            pin_memory=(self.device.type == "cuda"),
            drop_last=True,
            prefetch_factor=2,
            persistent_workers=(self.num_workers > 0),
        )
        self.val_loader = DataLoader(
            self.val_dataset,
            batch_size=self.batch_size,
            shuffle=False,
            num_workers=self.num_workers,
            pin_memory=(self.device.type == "cuda"),
            drop_last=False,
            prefetch_factor=2,
            persistent_workers=(self.num_workers > 0),
        )
        logger.info(
            "DataLoaders created: batch_size=%d, workers=%d, "
            "train_batches=%d, val_batches=%d",
            self.batch_size, self.num_workers,
            len(self.train_loader), len(self.val_loader),
        )

    def _reduce_batch_size(self) -> bool:
        """Halve batch size and recreate DataLoaders.

        Returns:
            True if reduction was possible, False if already at minimum.
        """
        new_bs = self.batch_size // 2
        if new_bs < 2:
            return False
        logger.warning("OOM detected -- reducing batch size: %d -> %d",
                        self.batch_size, new_bs)
        self.batch_size = new_bs
        torch.cuda.empty_cache()
        gc.collect()
        self._create_dataloaders()
        return True

    def train_epoch(self, epoch: int) -> Tuple[float, float]:
        """Run one training epoch.

        Args:
            epoch: Current epoch number (0-based).

        Returns:
            Tuple of (average_loss, accuracy).
        """
        self.model.train()
        running_loss = 0.0
        correct = 0
        total = 0

        for batch_idx, (images, labels) in enumerate(self.train_loader):
            images = images.to(self.device, non_blocking=True)
            labels = labels.to(self.device, non_blocking=True)

            self.optimizer.zero_grad(set_to_none=True)

            try:
                with torch.cuda.amp.autocast(enabled=self.use_amp):
                    outputs = self.model(images)
                    loss = self.criterion(outputs, labels)

                self.scaler.scale(loss).backward()
                self.scaler.step(self.optimizer)
                self.scaler.update()

            except RuntimeError as e:
                if "out of memory" in str(e).lower():
                    torch.cuda.empty_cache()
                    gc.collect()
                    if self._reduce_batch_size():
                        # Restart epoch with smaller batch
                        return self.train_epoch(epoch)
                    else:
                        raise RuntimeError(
                            "OOM even at batch_size=2. Reduce model or input size."
                        ) from e
                raise

            running_loss += loss.item() * images.size(0)
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

        avg_loss = running_loss / max(total, 1)
        accuracy = correct / max(total, 1)
        return avg_loss, accuracy

    @torch.no_grad()
    def validate_epoch(self) -> Tuple[float, float, float, float, float]:
        """Run validation and compute metrics.

        Returns:
            Tuple of (loss, accuracy, precision, recall, f1).
        """
        self.model.eval()
        running_loss = 0.0
        all_preds: List[int] = []
        all_labels: List[int] = []

        for images, labels in self.val_loader:
            images = images.to(self.device, non_blocking=True)
            labels = labels.to(self.device, non_blocking=True)

            with torch.cuda.amp.autocast(enabled=self.use_amp):
                outputs = self.model(images)
                loss = self.criterion(outputs, labels)

            running_loss += loss.item() * images.size(0)
            _, predicted = outputs.max(1)
            all_preds.extend(predicted.cpu().tolist())
            all_labels.extend(labels.cpu().tolist())

        total = max(len(all_labels), 1)
        avg_loss = running_loss / total

        # Compute metrics
        from sklearn.metrics import (
            accuracy_score, f1_score, precision_score, recall_score,
        )
        accuracy = accuracy_score(all_labels, all_preds)
        precision = precision_score(
            all_labels, all_preds, average="weighted", zero_division=0,
        )
        recall = recall_score(
            all_labels, all_preds, average="weighted", zero_division=0,
        )
        f1 = f1_score(
            all_labels, all_preds, average="weighted", zero_division=0,
        )

        return avg_loss, accuracy, precision, recall, f1

    def _save_checkpoint(self, epoch: int, val_accuracy: float) -> Path:
        """Save model checkpoint and manage checkpoint retention.

        Args:
            epoch: Current epoch number.
            val_accuracy: Validation accuracy for filename.

        Returns:
            Path to saved checkpoint.
        """
        ckpt_name = f"chart_vision_ep{epoch:03d}_acc{val_accuracy:.4f}.pt"
        ckpt_path = self.output_dir / ckpt_name

        torch.save({
            "epoch": epoch,
            "model_state_dict": self.model.state_dict(),
            "optimizer_state_dict": self.optimizer.state_dict(),
            "scheduler_state_dict": self.scheduler.state_dict(),
            "scaler_state_dict": self.scaler.state_dict(),
            "val_accuracy": val_accuracy,
            "batch_size": self.batch_size,
            "num_classes": self.model.num_classes,
        }, ckpt_path)

        self.checkpoint_paths.append(ckpt_path)
        logger.info("Checkpoint saved: %s", ckpt_path.name)

        # Prune old checkpoints (keep best N)
        if len(self.checkpoint_paths) > NUM_CHECKPOINTS_KEEP:
            oldest = self.checkpoint_paths.pop(0)
            if oldest.exists():
                oldest.unlink()
                logger.debug("Removed old checkpoint: %s", oldest.name)

        return ckpt_path

    def _get_gpu_memory_mb(self) -> float:
        """Get current GPU memory usage in MB."""
        if self.device.type == "cuda":
            return torch.cuda.memory_allocated(self.device) / (1024 * 1024)
        return 0.0

    def train(self, resume_checkpoint: Optional[str] = None) -> TrainingReport:
        """Full training loop with early stopping.

        Args:
            resume_checkpoint: Path to checkpoint file to resume from.

        Returns:
            TrainingReport with all metrics and training details.
        """
        t0 = time.time()
        start_epoch = 0

        # Resume from checkpoint if provided
        if resume_checkpoint is not None:
            ckpt = torch.load(resume_checkpoint, map_location=self.device,
                              weights_only=False)
            self.model.load_state_dict(ckpt["model_state_dict"])
            self.optimizer.load_state_dict(ckpt["optimizer_state_dict"])
            self.scheduler.load_state_dict(ckpt["scheduler_state_dict"])
            if "scaler_state_dict" in ckpt:
                self.scaler.load_state_dict(ckpt["scaler_state_dict"])
            start_epoch = ckpt["epoch"] + 1
            self.best_val_accuracy = ckpt.get("val_accuracy", 0.0)
            logger.info("Resumed from epoch %d (val_acc=%.4f)",
                         start_epoch, self.best_val_accuracy)

        trainable = self.model.get_trainable_params()
        total = self.model.get_total_params()
        logger.info(
            "Model params: %d trainable / %d total (%.1f%% frozen)",
            trainable, total, (1 - trainable / max(total, 1)) * 100,
        )
        logger.info(
            "Training: %d epochs, batch_size=%d, lr=%.2e",
            self.max_epochs, self.batch_size, self.lr,
        )

        best_model_path: Optional[Path] = None

        for epoch in range(start_epoch, self.max_epochs):
            epoch_t0 = time.time()

            # Train
            train_loss, train_acc = self.train_epoch(epoch)

            # Validate
            val_loss, val_acc, val_prec, val_rec, val_f1 = self.validate_epoch()

            # LR step
            current_lr = self.optimizer.param_groups[0]["lr"]
            self.scheduler.step()

            epoch_elapsed = time.time() - epoch_t0
            gpu_mem = self._get_gpu_memory_mb()

            # Record metrics
            metrics = TrainingMetrics(
                epoch=epoch,
                train_loss=train_loss,
                train_accuracy=train_acc,
                val_loss=val_loss,
                val_accuracy=val_acc,
                val_precision=val_prec,
                val_recall=val_rec,
                val_f1=val_f1,
                lr=current_lr,
                elapsed_sec=epoch_elapsed,
                gpu_memory_mb=gpu_mem,
            )
            self.epoch_metrics.append(metrics)

            logger.info(
                "Epoch %d/%d | Train: loss=%.4f acc=%.4f | "
                "Val: loss=%.4f acc=%.4f f1=%.4f | "
                "LR=%.2e | %.1fs | GPU=%.0fMB",
                epoch + 1, self.max_epochs,
                train_loss, train_acc,
                val_loss, val_acc, val_f1,
                current_lr, epoch_elapsed, gpu_mem,
            )

            # Check for improvement
            improved = False
            if val_acc > self.best_val_accuracy:
                self.best_val_accuracy = val_acc
                self.best_val_f1 = val_f1
                self.best_epoch = epoch
                self.epochs_without_improvement = 0
                improved = True
            else:
                self.epochs_without_improvement += 1

            # Save checkpoint every epoch
            ckpt_path = self._save_checkpoint(epoch, val_acc)
            if improved:
                best_model_path = ckpt_path

            # Early stopping
            if self.epochs_without_improvement >= self.patience:
                logger.info(
                    "Early stopping at epoch %d (no improvement for %d epochs)",
                    epoch + 1, self.patience,
                )
                break

            # Memory cleanup
            torch.cuda.empty_cache()
            gc.collect()

        total_elapsed = time.time() - t0

        # Save best model as final
        if best_model_path is not None and best_model_path.exists():
            final_path = self.output_dir / "chart_vision_best.pt"
            import shutil
            shutil.copy2(best_model_path, final_path)
            logger.info("Best model saved: %s (epoch %d, acc=%.4f)",
                         final_path, self.best_epoch, self.best_val_accuracy)

        # Build confusion matrix from last validation
        confusion = self._compute_confusion_matrix()

        # Build report
        report = TrainingReport(
            model_name="ChartPatternClassifier_ResNet50",
            num_classes=self.model.num_classes,
            class_names=self.train_dataset.class_names,
            total_epochs=len(self.epoch_metrics),
            best_epoch=self.best_epoch,
            best_val_accuracy=self.best_val_accuracy,
            best_val_f1=self.best_val_f1,
            epoch_metrics=self.epoch_metrics,
            train_samples=len(self.train_dataset),
            val_samples=len(self.val_dataset),
            total_elapsed_sec=total_elapsed,
            confusion_matrix=confusion,
        )

        # Save report
        self._save_report(report)

        logger.info("\n%s", report.summary())
        return report

    @torch.no_grad()
    def _compute_confusion_matrix(self) -> Optional[List[List[int]]]:
        """Compute confusion matrix on validation set.

        Returns:
            Confusion matrix as nested list, or None on error.
        """
        try:
            from sklearn.metrics import confusion_matrix

            self.model.eval()
            all_preds: List[int] = []
            all_labels: List[int] = []

            for images, labels in self.val_loader:
                images = images.to(self.device, non_blocking=True)
                with torch.cuda.amp.autocast(enabled=self.use_amp):
                    outputs = self.model(images)
                _, predicted = outputs.max(1)
                all_preds.extend(predicted.cpu().tolist())
                all_labels.extend(labels.cpu().tolist())

            cm = confusion_matrix(all_labels, all_preds)
            return cm.tolist()
        except Exception as e:
            logger.warning("Failed to compute confusion matrix: %s", e)
            return None

    def _save_report(self, report: TrainingReport) -> None:
        """Save training report as JSON.

        Args:
            report: TrainingReport to save.
        """
        report_path = self.output_dir / "training_report.json"
        data = {
            "model_name": report.model_name,
            "num_classes": report.num_classes,
            "class_names": report.class_names,
            "total_epochs": report.total_epochs,
            "best_epoch": report.best_epoch,
            "best_val_accuracy": report.best_val_accuracy,
            "best_val_f1": report.best_val_f1,
            "train_samples": report.train_samples,
            "val_samples": report.val_samples,
            "test_samples": report.test_samples,
            "total_elapsed_sec": report.total_elapsed_sec,
            "epoch_metrics": [
                {
                    "epoch": m.epoch,
                    "train_loss": m.train_loss,
                    "train_accuracy": m.train_accuracy,
                    "val_loss": m.val_loss,
                    "val_accuracy": m.val_accuracy,
                    "val_precision": m.val_precision,
                    "val_recall": m.val_recall,
                    "val_f1": m.val_f1,
                    "lr": m.lr,
                    "elapsed_sec": m.elapsed_sec,
                    "gpu_memory_mb": m.gpu_memory_mb,
                }
                for m in report.epoch_metrics
            ],
            "confusion_matrix": report.confusion_matrix,
        }
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)
        logger.info("Training report saved: %s", report_path)


# ============================================================
# INFERENCE
# ============================================================

def predict_chart(
    image_path: str,
    model_path: str = "models/vision/chart_vision_best.pt",
    device: Optional[str] = None,
) -> Dict[str, Any]:
    """Predict chart pattern from a single image.

    Args:
        image_path: Path to the chart image.
        model_path: Path to saved model checkpoint.
        device: Device string ("cuda", "cpu"). Auto-detected if None.

    Returns:
        Dict with keys:
            - pattern: str -- predicted pattern name
            - confidence: float -- probability of predicted pattern
            - probabilities: Dict[str, float] -- all class probabilities
    """
    from PIL import Image

    # Device
    if device is None:
        dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        dev = torch.device(device)

    # Load checkpoint
    ckpt = torch.load(model_path, map_location=dev, weights_only=False)
    num_classes = ckpt["num_classes"]

    # Rebuild model
    model = ChartPatternClassifier(num_classes=num_classes, pretrained=False)
    model.load_state_dict(ckpt["model_state_dict"])
    model.to(dev)
    model.eval()

    # Load and transform image
    transform = get_val_transforms()
    img = Image.open(image_path).convert("RGB")
    img_tensor = transform(img).unsqueeze(0).to(dev)

    # Inference
    with torch.no_grad():
        with torch.cuda.amp.autocast(enabled=(dev.type == "cuda")):
            logits = model(img_tensor)
            probs = torch.softmax(logits, dim=1).squeeze(0)

    # Need class names from training -- try to load from report
    report_path = Path(model_path).parent / "training_report.json"
    if report_path.exists():
        with open(report_path, "r", encoding="utf-8") as f:
            report_data = json.load(f)
        class_names = report_data.get("class_names", [])
    else:
        class_names = [f"class_{i}" for i in range(num_classes)]

    probs_np = probs.cpu().numpy()
    pred_idx = int(probs_np.argmax())
    confidence = float(probs_np[pred_idx])

    probabilities = {
        class_names[i]: float(probs_np[i])
        for i in range(len(class_names))
    }

    # Cleanup
    del model, img_tensor, logits, probs
    torch.cuda.empty_cache()
    gc.collect()

    return {
        "pattern": class_names[pred_idx] if pred_idx < len(class_names) else f"class_{pred_idx}",
        "confidence": confidence,
        "probabilities": probabilities,
    }
