#!/usr/bin/env python3
"""
SCRIPT NAME: strategies.py
====================================
Execution Location: K:\\_DEV_MVP_2026\\Market_Hawk_3\\backtesting\\
Purpose: Pluggable trading strategies for the backtesting engine.
         Includes classic TA strategies + Market Hawk agent consensus strategy.
Hardware Optimization: Intel i7-9700F, NVIDIA GTX 1070 8GB VRAM, 64GB DDR4
Creation Date: 2026-03-01
"""

import logging
from abc import ABC, abstractmethod
from typing import Optional, Dict, Any
from dataclasses import dataclass
from enum import Enum

import numpy as np
import pandas as pd

logger = logging.getLogger("market_hawk.backtest.strategies")


# ============================================================
# SIGNAL TYPES
# ============================================================

class Signal(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class TradeSignal:
    """Signal generated by a strategy."""
    signal: Signal
    confidence: float = 0.5       # 0.0 to 1.0
    stop_loss_pct: float = 0.02   # 2% default
    take_profit_pct: float = 0.04 # 4% default
    position_size: float = 0.02   # 2% of portfolio
    reason: str = ""
    metadata: Dict[str, Any] = None

    def __post_init__(self):
        if self.metadata is None:
            self.metadata = {}


# ============================================================
# BASE STRATEGY
# ============================================================

class StrategyBase(ABC):
    """
    Abstract base class for all backtesting strategies.

    Subclass this and implement:
        - name: str property
        - generate_signal(df, idx) -> TradeSignal
        - optionally: on_init(df) for pre-computation
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name for reporting."""
        ...

    def on_init(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Called once before backtesting starts.
        Pre-compute indicators here and add them as columns.
        Return the modified DataFrame.
        """
        return df

    @abstractmethod
    def generate_signal(self, df: pd.DataFrame, idx: int) -> TradeSignal:
        """
        Generate a trading signal for the current bar.

        Args:
            df: Full DataFrame with indicators
            idx: Current bar index (integer position)

        Returns:
            TradeSignal (BUY, SELL, or HOLD)
        """
        ...


# ============================================================
# MA CROSSOVER STRATEGY
# ============================================================

class MACrossover(StrategyBase):
    """
    Moving Average Crossover (Golden/Death Cross).

    BUY:  Fast MA crosses above Slow MA
    SELL: Fast MA crosses below Slow MA
    """

    def __init__(self, fast_period: int = 20, slow_period: int = 50,
                 use_ema: bool = True,
                 sl_pct: float = 0.02, tp_pct: float = 0.04):
        self.fast_period = fast_period
        self.slow_period = slow_period
        self.use_ema = use_ema
        self.sl_pct = sl_pct
        self.tp_pct = tp_pct

    @property
    def name(self) -> str:
        ma_type = "EMA" if self.use_ema else "SMA"
        return f"{ma_type}_{self.fast_period}/{self.slow_period}_Cross"

    def on_init(self, df: pd.DataFrame) -> pd.DataFrame:
        close = df["Close"]
        if self.use_ema:
            df["_fast_ma"] = close.ewm(span=self.fast_period, adjust=False).mean()
            df["_slow_ma"] = close.ewm(span=self.slow_period, adjust=False).mean()
        else:
            df["_fast_ma"] = close.rolling(self.fast_period).mean()
            df["_slow_ma"] = close.rolling(self.slow_period).mean()
        return df

    def generate_signal(self, df: pd.DataFrame, idx: int) -> TradeSignal:
        if idx < 1:
            return TradeSignal(Signal.HOLD)

        fast_now = df["_fast_ma"].iloc[idx]
        slow_now = df["_slow_ma"].iloc[idx]
        fast_prev = df["_fast_ma"].iloc[idx - 1]
        slow_prev = df["_slow_ma"].iloc[idx - 1]

        if pd.isna(fast_now) or pd.isna(slow_now):
            return TradeSignal(Signal.HOLD)

        # Golden cross
        if fast_prev <= slow_prev and fast_now > slow_now:
            spread = abs(fast_now - slow_now) / slow_now
            conf = min(0.5 + spread * 20, 0.95)
            return TradeSignal(
                signal=Signal.BUY,
                confidence=conf,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"Golden Cross: fast={fast_now:.4f} > slow={slow_now:.4f}",
            )

        # Death cross
        if fast_prev >= slow_prev and fast_now < slow_now:
            spread = abs(slow_now - fast_now) / slow_now
            conf = min(0.5 + spread * 20, 0.95)
            return TradeSignal(
                signal=Signal.SELL,
                confidence=conf,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"Death Cross: fast={fast_now:.4f} < slow={slow_now:.4f}",
            )

        return TradeSignal(Signal.HOLD)


# ============================================================
# RSI MEAN REVERSION
# ============================================================

class RSIMeanReversion(StrategyBase):
    """
    RSI Mean Reversion Strategy.

    BUY:  RSI drops below oversold level then starts recovering
    SELL: RSI rises above overbought level then starts declining
    """

    def __init__(self, period: int = 14,
                 oversold: float = 30.0, overbought: float = 70.0,
                 sl_pct: float = 0.015, tp_pct: float = 0.03):
        self.period = period
        self.oversold = oversold
        self.overbought = overbought
        self.sl_pct = sl_pct
        self.tp_pct = tp_pct

    @property
    def name(self) -> str:
        return f"RSI_{self.period}_MeanRev({self.oversold}/{self.overbought})"

    def on_init(self, df: pd.DataFrame) -> pd.DataFrame:
        delta = df["Close"].diff()
        gain = delta.where(delta > 0, 0.0)
        loss = -delta.where(delta < 0, 0.0)
        avg_gain = gain.rolling(self.period).mean()
        avg_loss = loss.rolling(self.period).mean()
        rs = avg_gain / avg_loss
        df["_rsi"] = 100 - (100 / (1 + rs))
        return df

    def generate_signal(self, df: pd.DataFrame, idx: int) -> TradeSignal:
        if idx < 2:
            return TradeSignal(Signal.HOLD)

        rsi_now = df["_rsi"].iloc[idx]
        rsi_prev = df["_rsi"].iloc[idx - 1]
        rsi_prev2 = df["_rsi"].iloc[idx - 2]

        if pd.isna(rsi_now) or pd.isna(rsi_prev):
            return TradeSignal(Signal.HOLD)

        # Oversold bounce: RSI was below oversold, now recovering
        if rsi_prev2 < self.oversold and rsi_prev < self.oversold and rsi_now > self.oversold:
            depth = (self.oversold - min(rsi_prev, rsi_prev2)) / self.oversold
            conf = min(0.55 + depth, 0.90)
            return TradeSignal(
                signal=Signal.BUY,
                confidence=conf,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"RSI oversold bounce: {rsi_prev:.1f} -> {rsi_now:.1f}",
            )

        # Overbought reversal: RSI was above overbought, now declining
        if rsi_prev2 > self.overbought and rsi_prev > self.overbought and rsi_now < self.overbought:
            depth = (max(rsi_prev, rsi_prev2) - self.overbought) / (100 - self.overbought)
            conf = min(0.55 + depth, 0.90)
            return TradeSignal(
                signal=Signal.SELL,
                confidence=conf,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"RSI overbought reversal: {rsi_prev:.1f} -> {rsi_now:.1f}",
            )

        return TradeSignal(Signal.HOLD)


# ============================================================
# BOLLINGER BANDS BREAKOUT
# ============================================================

class BollingerBreakout(StrategyBase):
    """
    Bollinger Bands Breakout/Reversion.

    BUY:  Price touches lower band and starts bouncing
    SELL: Price touches upper band and starts declining
    """

    def __init__(self, period: int = 20, num_std: float = 2.0,
                 sl_pct: float = 0.02, tp_pct: float = 0.03):
        self.period = period
        self.num_std = num_std
        self.sl_pct = sl_pct
        self.tp_pct = tp_pct

    @property
    def name(self) -> str:
        return f"BB_{self.period}_{self.num_std}std"

    def on_init(self, df: pd.DataFrame) -> pd.DataFrame:
        close = df["Close"]
        df["_bb_mid"] = close.rolling(self.period).mean()
        bb_std = close.rolling(self.period).std()
        df["_bb_upper"] = df["_bb_mid"] + self.num_std * bb_std
        df["_bb_lower"] = df["_bb_mid"] - self.num_std * bb_std
        df["_bb_pct"] = (close - df["_bb_lower"]) / (df["_bb_upper"] - df["_bb_lower"])
        return df

    def generate_signal(self, df: pd.DataFrame, idx: int) -> TradeSignal:
        if idx < 1:
            return TradeSignal(Signal.HOLD)

        pct_now = df["_bb_pct"].iloc[idx]
        pct_prev = df["_bb_pct"].iloc[idx - 1]
        close = df["Close"].iloc[idx]

        if pd.isna(pct_now) or pd.isna(pct_prev):
            return TradeSignal(Signal.HOLD)

        # Bounce from lower band
        if pct_prev < 0.05 and pct_now > 0.05:
            return TradeSignal(
                signal=Signal.BUY,
                confidence=0.65,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"BB lower band bounce: {pct_prev:.2f} -> {pct_now:.2f}",
            )

        # Rejection from upper band
        if pct_prev > 0.95 and pct_now < 0.95:
            return TradeSignal(
                signal=Signal.SELL,
                confidence=0.65,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"BB upper band rejection: {pct_prev:.2f} -> {pct_now:.2f}",
            )

        return TradeSignal(Signal.HOLD)


# ============================================================
# MACD HISTOGRAM STRATEGY
# ============================================================

class MACDHistogram(StrategyBase):
    """
    MACD Histogram reversal strategy.

    BUY:  Histogram crosses from negative to positive
    SELL: Histogram crosses from positive to negative
    """

    def __init__(self, fast: int = 12, slow: int = 26, signal: int = 9,
                 sl_pct: float = 0.02, tp_pct: float = 0.04):
        self.fast = fast
        self.slow = slow
        self.signal_period = signal
        self.sl_pct = sl_pct
        self.tp_pct = tp_pct

    @property
    def name(self) -> str:
        return f"MACD_{self.fast}_{self.slow}_{self.signal_period}"

    def on_init(self, df: pd.DataFrame) -> pd.DataFrame:
        close = df["Close"]
        ema_fast = close.ewm(span=self.fast, adjust=False).mean()
        ema_slow = close.ewm(span=self.slow, adjust=False).mean()
        df["_macd"] = ema_fast - ema_slow
        df["_macd_signal"] = df["_macd"].ewm(span=self.signal_period, adjust=False).mean()
        df["_macd_hist"] = df["_macd"] - df["_macd_signal"]
        return df

    def generate_signal(self, df: pd.DataFrame, idx: int) -> TradeSignal:
        if idx < 1:
            return TradeSignal(Signal.HOLD)

        hist_now = df["_macd_hist"].iloc[idx]
        hist_prev = df["_macd_hist"].iloc[idx - 1]

        if pd.isna(hist_now) or pd.isna(hist_prev):
            return TradeSignal(Signal.HOLD)

        # Bullish crossover
        if hist_prev < 0 and hist_now > 0:
            return TradeSignal(
                signal=Signal.BUY,
                confidence=0.60,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"MACD bullish: hist {hist_prev:.4f} -> {hist_now:.4f}",
            )

        # Bearish crossover
        if hist_prev > 0 and hist_now < 0:
            return TradeSignal(
                signal=Signal.SELL,
                confidence=0.60,
                stop_loss_pct=self.sl_pct,
                take_profit_pct=self.tp_pct,
                reason=f"MACD bearish: hist {hist_prev:.4f} -> {hist_now:.4f}",
            )

        return TradeSignal(Signal.HOLD)


# ============================================================
# AGENT CONSENSUS STRATEGY (uses Market Hawk Brain)
# ============================================================

class AgentConsensusStrategy(StrategyBase):
    """
    Market Hawk 5-Agent Consensus Strategy.

    Runs the full Brain pipeline (ML Signal, Knowledge Advisor,
    Risk Manager, News Analyzer, Security Guard) and uses
    the consensus score for trade decisions.

    This is the strategy that makes Market Hawk unique —
    it backtests the actual multi-agent system.
    """

    def __init__(self, consensus_threshold: float = 0.30,
                 sl_pct: float = 0.02, tp_pct: float = 0.04):
        self.consensus_threshold = consensus_threshold
        self.sl_pct = sl_pct
        self.tp_pct = tp_pct
        self.brain = None
        self._feature_engineer = None

    @property
    def name(self) -> str:
        return f"AgentConsensus_thresh{self.consensus_threshold}"

    def on_init(self, df: pd.DataFrame) -> pd.DataFrame:
        """Pre-compute all 60 features the ML engine needs."""
        from data.market_data_fetcher import MarketDataFetcher
        self._feature_engineer = MarketDataFetcher()

        # Engineer features on the full historical dataset
        df_features = self._feature_engineer.engineer_features(df.copy())

        # Merge features back (they'll have the same index)
        for col in df_features.columns:
            if col not in df.columns:
                df[col] = df_features[col].values

        return df

    def generate_signal(self, df: pd.DataFrame, idx: int) -> TradeSignal:
        """
        For backtesting, we use a simplified consensus based on
        the pre-computed features rather than calling async agents.
        This is much faster and reproducible.
        """
        if idx < 200:  # Need enough history for indicators
            return TradeSignal(Signal.HOLD)

        try:
            # Continuous-score ensemble vote from indicators
            # Each voter outputs a score in [-1.0, +1.0] for granular consensus
            votes = []

            # Vote 1: RSI — continuous scoring
            # Maps RSI 0→100 to score +1.0→-1.0 (low RSI = bullish)
            rsi = df.get("RSI", df.get("rsi", pd.Series([50])))
            if isinstance(rsi, pd.Series) and idx < len(rsi):
                rsi_val = rsi.iloc[idx]
                if not pd.isna(rsi_val):
                    # Linear map: RSI 30→+0.8, RSI 50→0, RSI 70→-0.8
                    rsi_score = np.clip((50 - rsi_val) / 25.0, -1.0, 1.0)
                    votes.append(("RSI", rsi_score))

            # Vote 2: MACD histogram — direction + magnitude
            macd_hist = df.get("MACD_histogram", df.get("macd", pd.Series([0])))
            if isinstance(macd_hist, pd.Series) and idx < len(macd_hist):
                mh = macd_hist.iloc[idx]
                if not pd.isna(mh):
                    # Normalize by recent range for comparable scale
                    lookback = max(0, idx - 50)
                    recent_hist = macd_hist.iloc[lookback:idx+1].dropna()
                    if len(recent_hist) > 5:
                        hist_range = recent_hist.abs().quantile(0.95)
                        if hist_range > 0:
                            macd_score = np.clip(mh / hist_range, -1.0, 1.0)
                        else:
                            macd_score = 1.0 if mh > 0 else -1.0
                    else:
                        macd_score = 1.0 if mh > 0 else -1.0
                    votes.append(("MACD", macd_score))

            # Vote 3: MA trend — spread strength
            sma20 = df.get("SMA_20", pd.Series([0]))
            sma50 = df.get("SMA_50", pd.Series([0]))
            if isinstance(sma20, pd.Series) and idx < len(sma20):
                s20 = sma20.iloc[idx]
                s50 = sma50.iloc[idx] if isinstance(sma50, pd.Series) and idx < len(sma50) else s20
                if not pd.isna(s20) and not pd.isna(s50) and s50 != 0:
                    # Score proportional to spread (capped at ±2%)
                    spread_pct = (s20 - s50) / s50
                    ma_score = np.clip(spread_pct / 0.02, -1.0, 1.0)
                    votes.append(("MA_Trend", ma_score))

            # Vote 4: Bollinger position — continuous
            bb_pos = df.get("BB_position", pd.Series([0.5]))
            if isinstance(bb_pos, pd.Series) and idx < len(bb_pos):
                bp = bb_pos.iloc[idx]
                if not pd.isna(bp):
                    # Map: 0.0→+1.0 (oversold), 0.5→0, 1.0→-1.0 (overbought)
                    bb_score = np.clip(1.0 - 2.0 * bp, -1.0, 1.0)
                    votes.append(("BB", bb_score))

            # Vote 5: Volume confirmation (amplifier, not directional)
            vol_ratio = df.get("volume_ratio", pd.Series([1.0]))
            if isinstance(vol_ratio, pd.Series) and idx < len(vol_ratio):
                vr = vol_ratio.iloc[idx]
                if not pd.isna(vr):
                    # High volume amplifies existing signal direction
                    vol_amplifier = np.clip((vr - 1.0) / 2.0, 0.0, 1.0)
                    # Use direction of other votes as volume's direction
                    if len(votes) > 0:
                        direction = sum(v[1] for v in votes) / len(votes)
                        vol_score = direction * vol_amplifier
                    else:
                        vol_score = 0.0
                    votes.append(("Volume", vol_score))

            if not votes:
                return TradeSignal(Signal.HOLD)

            # Calculate consensus
            total_score = sum(v[1] for v in votes) / len(votes)

            if total_score > self.consensus_threshold:
                return TradeSignal(
                    signal=Signal.BUY,
                    confidence=min(abs(total_score), 0.95),
                    stop_loss_pct=self.sl_pct,
                    take_profit_pct=self.tp_pct,
                    reason=f"Agent consensus={total_score:.3f} ({len(votes)} votes)",
                    metadata={"votes": {v[0]: v[1] for v in votes}},
                )
            elif total_score < -self.consensus_threshold:
                return TradeSignal(
                    signal=Signal.SELL,
                    confidence=min(abs(total_score), 0.95),
                    stop_loss_pct=self.sl_pct,
                    take_profit_pct=self.tp_pct,
                    reason=f"Agent consensus={total_score:.3f} ({len(votes)} votes)",
                    metadata={"votes": {v[0]: v[1] for v in votes}},
                )

            return TradeSignal(Signal.HOLD)

        except Exception:
            logger.debug("Signal generation error at idx %d", idx, exc_info=True)
            return TradeSignal(Signal.HOLD)
